### ISSUE TITLE
Problems with python plugin/module

### ISSUE THREAD

**Issue by AlexSokoliuk** [gyoto/Gyoto#10]
Hi. When I installed your package Gyoto and tried to run some python scenarios with the use of .py defined metric tensor, I encounter error. I type `gyoto example-python.xml \!output.fits` and receive error:
`
Reading parameter file: example-python.xml
In gyoto.C: Error getting Scenery: Register.C:244 in Gyoto::SmartPointer<Gyoto::SmartPointee> (* Gyoto::Register::Entry::getSubcontractor(std::string, std::string&, int))(Gyoto::FactoryMessenger*, const std::vector<std::__cxx11::basic_string<char> >&): Unregistered kind: Python
`
How could it be fixed? I use only official examples, so I assume I do not need to define something additionally (little remark: other scenarios, that are not defined with the use of python are running well).

**Comment by paumard** [comment]
Thanks for your comment. Indeed we should add a README file in this folder. 

"Unregistered kind: Python" indicates that the Python plug-in is not loaded. This XML file requires the Python plugin and the standard plugin. Assuming you compiled with python3, this should do:

gyoto --plugins=python3,stdplug example-python.xml output.fits

**Comment by AlexSokoliuk** [comment]
Thank you so much for that helpful and fast response! Sorry for such a silly question :)
