### ISSUE TITLE
Update autotools

### ISSUE THREAD

**Issue by ryandesign** [gyoto/Gyoto#13]
The generated autotools files in the repository (configure, Makefile.in, etc.) were generated with autoconf 2.69, automake 1.16.3, and libtool 2.4.2. These versions are outdated. Current versions are autoconf 2.71, automake 1.16.5, and libtool 2.4.7.

One consequence of using outdated autotools is that gyoto fails to build on macOS 11 and later because libtool versions prior to 2.4.7 contained the [incorrect assumption](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=44605) that all macOS versions begin with "10."

Please use current versions of autotools for future gyoto releases.

In addition, you've copied some libtool files, like libtool.m4, into your project, in multiple places (and for some reason they differ even though they have the same "serial"). Please update your copied libtool m4 files from the latest libtool as well.

**Comment by paumard** [comment]
Thanks, will do ASAP.

**Comment by paumard** [comment]
Done
