### ISSUE TITLE
Isuue when extending gyoto in de-sitter spacetime

### ISSUE THREAD

**Issue by shuluo-stack** [gyoto/Gyoto#22]
Dear author,
Sorry for bothering you. I tried to extend gyoto in a metric of asymptotic de-sitter spacetime, and following previous instructions I set  guarantees for stopping the integration when it is close to two horizons, the event horizon or cosmological horizon. Also I ensured that my metric and christofel symbol have no spelling mistakes. Yet there still exist error when computing .xml, just like some users before I received plenty of "norm is drifting - with norm, normref=........." , and I don't know the reason. Are there any basic problems when extending this in de-sitter spacetime?
My plugin and .xml is in the [annex.]
[KerrBL1.zip](https://github.com/user-attachments/files/16775856/KerrBL1.zip)

I would appreciate if you can have a look.

**Comment by shuluo-stack** [comment]
Dear author,
I hope you have already seen my comments.  Still I cannot solve this problem and I hope you can give me some hint at least. I have spent last month on learning and using your software. Looking forward to your reply.
Luo

**Comment by shuluo-stack** [comment]
Dear author,
I think I have already solved the issue, and it is just a simple grammar mistake. I am sorry for any bothering and you don't need to care this any longer. No reply needed.
Luo

**Comment by paumard** [comment]
Dear Luo, I'm glad that you have been able to sort it out and sorry that I didn't find the time to help you last week. Cheers.
