### ISSUE TITLE
I encountered the warning ：”SEVERE: Photon::hit: too many iterations (100001 vs. 100000), break.“ again when I used my metric to draw the PageThorne disk 

### ISSUE THREAD

**Issue by Dirac666666** [gyoto/Gyoto#24]
Dear author,
Hi, I'm sorry to bother you with another question

last week ，I used my metric to drew thindisk and I encountered the warning :"SEVERE: Photon::hit: too many iterations (100001 vs. 100000), break." therefore I took your suggestion and added the isStopCondition() function into my metric.C. With your help, I solved the
warning.
but I encountered the warning ：”SEVERE: Photon::hit: too many iterations (100001 vs. 100000), break.“ again , when I used my metric to draw the PageThorne disk .

I am very confused and very curious, what goes wrong.
Do you have any other functions used to terminate the program, or is the isStopCondition() function used incorrectly?

The specific details, such as the images I get, my plugins, and the xml files , I put in the zip package 
[plugins.zip](https://github.com/user-attachments/files/17001593/plugins.zip)

I would be grateful if you, the great author, could reply to me, and wish you are happy every day

**Comment by Dirac666666** [comment]
Dear author,
I also found another problem, I change the values of the parameters in my metric, for example in the case of Ww=0, Aa=-0.2, I get an image like this, as follows
[PageThornedisk](https://github.com/user-attachments/assets/ac07d93f-8a05-4fa5-8cf5-819bc16d2905)
When I looked at the black hole shadow, I found that there are scattered discontinuous white dots around the photon ring, and these white dots form a ring
When I examined these white dots, I found that their values are nan in ds9
therefore I ran Gyoto in debug mode for a single pixel:
`gyoto -T1 PageThornedisk_hyb.xml \!PageThornedisk_hyb_test.fits --debug --imin=287 --imax=287 --jmin=323 --jmax=323`
and I got some  data in this picture
[value=nan](https://github.com/user-attachments/assets/461721df-98f1-4927-9a2b-2a632554a796)
However, through analysis, I did not find out why their values are nan. According to the metric is spherically symmetric, if there is a physical parameter and it's value is nan near the photon ring, then there should be a white ring around the photon ring, not some scattered white dots
If author is available, I am very much looking forward to your reply
[new plugins.zip](https://github.com/user-attachments/files/17023769/new.plugins.zip)

**Comment by paumard** [comment]
Hi,
Looking at your first issue first: I attach a debug log for one pixel where the warning occurs produced with:
`gyoto --jmin=200 --jmax=200 --imin=250 --imax=250 -T1 --debug git/Gyoto/33.xml \!33.fits > 33.log 2>&1`

(cut where the first nans appear)

This photon stalls at `pos=[-962.443,2.89769,2.36095,6.2704]`, does that ring a bell?

[33-log-snipped.txt](https://github.com/user-attachments/files/17381168/33-log-snipped.txt)

**Comment by Dirac666666** [comment]
thank you very much !!!

I have solved the nan in the second problem above，and the first problem still confused me  

Yes, I know the second component of pos=[-962.443,2.89769,2.36095,6.2704] is 2.89769 that is the horizon,  and I have used the IsStopCondition() function to draw PageThornedisk, but I still encountered the warning :"SEVERE: Photon::hit: too many iterations (100001 vs. 100000), break."

my code as follows 

```
GYOTO_PROPERTY_START(HYB,
                     "Metric around a rotating black-hole, in spherical Boyer-Lindquist coordinates. Cf. Lamy et al. 2018, https://arxiv.org/abs/1802.01635")
GYOTO_PROPERTY_DOUBLE(HYB, Ww, Ww,
                      "ww parameter (adimensioned, 0).")

GYOTO_PROPERTY_DOUBLE(HYB, Aa, Aa,
		      "Aa parameter (adimensioned, 0).")
GYOTO_PROPERTY_DOUBLE(HYB, RH, RH,
                      "RH parameter is the Radius of Horizon (adimensioned, 2).")		      
GYOTO_PROPERTY_DOUBLE(HYB, HorizonSecurity, horizonSecurity,
		      "Thickness of sink layer around horizon (geometrical units, 0.01).")     

GYOTO_PROPERTY_END(HYB, Generic::properties)
#define GYOTO_HYB_HORIZON_SECURITY 1e-2
```

```
HYB::HYB() :
Generic(GYOTO_COORDKIND_SPHERICAL, "HYB"),
  Ww_(0.),Aa_(0.),RH_(2.),rsink_(2.+GYOTO_HYB_HORIZON_SECURITY),
  drhor_(GYOTO_HYB_HORIZON_SECURITY)
{}

// default copy constructor should be fine
HYB * HYB::clone () const { return new HYB(*this); }



void HYB::Ww(const double w) {
 
  Ww_=w;
  
  tellListeners();
}
double HYB::Ww() const { return Ww_ ; }




void HYB::Aa(const double a) {
  Aa_=a;
  
  tellListeners();
}
// Accessors
double HYB::Aa() const { return Aa_ ; }

void HYB::RH(const double rh) {
  RH_=rh;
  
tellListeners();
}
 //Accessors
double HYB::RH() const { return RH_ ; }

```
```
void HYB::horizonSecurity(const double drhor) {
  drhor_=drhor;
  rsink_=RH_+drhor_;
  tellListeners();
}
double HYB::horizonSecurity() const {return drhor_; }

int HYB::isStopCondition(double const * const coord) const {
 return coord[1] < rsink_ ;
}

```
`
<Metric plugin="nmsl" kind = "HYB">
    <Ww> 0.3333 </Ww>
    <Aa> 0.4 </Aa>
    <RH> 2.9 </RH>
  </Metric>
`
I set the value of RH to 2.9  in  33.xml file, if my usage about the isstopcondition is correct ,then I should not encounter this warning

**Comment by paumard** [comment]
Nailed it: in isStopCondition, you compare to rsink_, but rsink_ is not updated when you set RH. Fix:
```
void HYB::RH(const double rh) {
  RH_=rh;
  rsink_=RH_+drhor_;
  tellListeners();
}
```
On a side note: Gyoto provides a bunch of facilities to help debugging. Among those are the [GYOTO_DEBUG* family of preprocessor macros](https://gyoto.obspm.fr/_gyoto_defs_8h.html#a16e0e6bc14859601c47ca51a542913d6). I have used GYTO_DEBUG_THIS_EXPR in isStopCondition to unconditionally print out some information:
```
int HYB::isStopCondition(double const * const coord) const {
  GYOTO_DEBUG_THIS_EXPR(coord[1]);
  GYOTO_DEBUG_THIS_EXPR(rsink_);
  return coord[1] < rsink_ ;
}
```
which has shown me that rsink_ was still at 2.01. Once this debugging work is finished, I usually keep such line, removing "THIS_", so that the message is only printed in debug mode.

Cheers.
