### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by raimundomartins** [gyoto/Gyoto#4]
Hello,
During installation of Gyoto I encountered two issues:
 1. aclocal.m4 forces the use of version 1.14 which I (and likely many others) don't have access to through my package manager, only 1.11 and 1.15 (I'm using ubuntu 16.10). I had to manually change the version number.
 2. make install doesn't run ldconfig when finished, so when I ran gyoto it complained about missing libraries. It was a quick fix for me, but might this confuse others.

**Comment by paumard** [comment]
Hi,
Thanks for your interest.
Have you followed the instructions in INSTALL.Gyoto?

aclocal.m4 is used for generating configure from configure.ac, which you should not have to do. Some of the autotools stuff gets regenerated automatically when the timestamps of the various files get mixed up, this is why INSTALL.Gyoto tells you to run post-git-merge.

If you need to recreate configure, then also recreate aclocal.m4 using autoreconf or aclocal.

Likewise, INSTALL.Gyoto instructs you to run ldconfig. Running ldconfig has to be done as root, and only when installing in certain places. It does not belong in `make install'.

Regards, Thibaut.

**Comment by raimundomartins** [comment]
Ah, that file appears to have information which could have save me some time :)

Sadly I only checked http://github.com/gyoto/Gyoto/blob/master/INSTALL as it's the website linked in http://gyoto.obspm.fr/ 
"More information on installing Gyoto is available [here] as well as in the user manual below."
The user manual also did not mention anything useful to this issue.

In the end maybe it's just an out-of-date link?

**Comment by paumard** [comment]
Thanks for letting me know. I've updated the webpage and INSTALL.Gyoto (now INSTALL.Gyoto.md...) 

I'll double check the manual. It should be updated nightly, but apparently it hasn't been for years.

Does that look better to you?



Regards, Thibaut.

**Comment by egourgoulhon** [comment]
I've checked the crontab on the web server: the web page should be updated every night at 0:26 am.

**Comment by egourgoulhon** [comment]
I've checked the crontab on the web server: the web page should be updated every night at 0:26 am.

**Comment by egourgoulhon** [comment]
I've checked the crontab on the web server: the web page should be updated every night at 0:26 am.

**Comment by egourgoulhon** [comment]
I've checked the crontab on the web server: the web page should be updated every night at 0:26 am.

**Comment by paumard** [comment]
Thanks Éric, I've just updated the scripts to achieve this ;-)

**Comment by raimundomartins** [comment]
Intallation instructions are now much more useful. Thank you! :)
